env:
- DATABASE_NAME=task_buster DATABASE_USER=postgres NOSSL=1 DJANGO_SETTINGS_MODULE="taskbuster.settings.testing"
language: python
python:
- '3.4'
install: pip install -r ./requirements/testing.txt
before_script:
- psql -c 'create database task_buster;' -U postgres
- python manage.py syncdb --noinput
- python manage.py migrate --noinput
- python manage.py runserver 0.0.0.0:8000 &
script: python manage.py test functional_tests
before_install:
- openssl aes-256-cbc -K $encrypted_bc888766e2a8_key -iv $encrypted_bc888766e2a8_iv -in fixtures.tar.enc -out fixtures.tar -d
- tar xvf fixtures.tar
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
