env:
  global:

    - DATABASE_NAME=task_buster DATABASE_USER=postgres NOSSL=1 DJANGO_SETTINGS_MODULE="taskbuster.settings.testing"
    - secure: i8EIabdYBg+uUdHk+KAOxfT640d3eLiyYn4sesUHroBp8yuSgsfrUWMPABRfovz6BudoX/lRousN0FM+K4uksvci2wx2ol4anmKAnhnELb51bquPo2vgYYvlpLfdy0IVOjgyWA0XUR8YdnqaxW8Fu8BZvOL0oYuJnWpbQwXuNsVkoqZ9IpIbyLmKYvNL1R8QWBy9phjbPedJ8GeuVjTRcN4Tl2VM7+H6z4rT70HfH3fGSXJP8R9SeiY43lQNTo38j1g3iJAtDwr6inJ28KNnWpwwr+/YPtkhSrsZUnjd8pwKm6Ls5e/jv5k+nXiYBJzJybdBJ1i1ReZnx5WTeUMlICLp0qiadL8odiNVblIBDvsDB5R/fFl86giG8q7HUS7Y65jWORPM/l6MXVp2xRb6M86pKuMSUsq+GDgWPPuWo7hnS5HHMOyhuEPgs8vL4dq/5NcVGGqlKePZYzP8jKllGm/Hjue5YkpC4XTukcFI4Z3yKn+KaKoZ/uCQSzJwMuK00aSMWOwjNp2YTNgFdOYwTPsfA9Q2bhzVThX9iz32aPjeqWKoFGKMP/nWmURJX8ILnkhJwQ+uh2uNu/Lld83s4F0xnLCw5ozOyNZLDlj4RjSXF1ulQW4VyTe9v9/m65JFo1NtMNxdRketHjE2g3juSgfptMJ0ezNlugXF3GQbJNo=
    - secure: Xnp/6cjD1E8OjgYtUxx5TJSfanZnk93B+kbZyViEizISxo+Fd5UXydlsFjN93FQ3jYLSxc/vWOA4BNb1MGTAI/p0h0ecyLbrfwJqyb11NLRmr/CWH9CzM6x6fOgtR5tz7xLbRO1WYieMAvuBJReL/FZi37qvhKmfSCJvFn5VghNATSIedm8UA79aCWvQrvXSrCDY/+mIXaaOBXjrq5kJIuVEonUijHX96eVOnXvUzqzZBh96Rb1Wu+REpkJaMrYzqjIROrHwENdioBJgjZ6KxhEc2O/PBMaXO1Fz4uDMdVD8XWCrUNZo6pUA14UWtTGYpgzZHdMkKj36V+XtA2aTCGvyF1grP9g/spcruOX5NTAgIz9nErj2Nq05VBEV1H+v7jqq0Hh8isu/OiNGtEviVgNBgHf7Y+Ktn21vVR16AAhQqVQNtazUXVqCzkBKCR4A3r11W24nraZCp+fi4vLi4hR3Fii+OVKS73WEAoSJh9oDpDZr9AIplZHMqLnFa3OOIA3pu7p55odncyXvl5+BkSr5hYO45bCnie8YKbTt9uYEWVt1KaSHNUdTygd/IntVliU1kMO5aHPztw1fsbu4+SgnEGg/N3OEnoZX5su5/JWShatppssKcS/UMkIz28fphve/rxOOgsLne6atjspZAW0/oA3F28KxOzRKH8OFq4o=

addons:
  sauce_connect: true

language: python
python:
- '3.4'
install: pip install -r ./requirements/testing.txt
before_script:
- psql -c 'create database task_buster;' -U postgres
- python manage.py syncdb --noinput
- python manage.py migrate --noinput
- python manage.py runserver 0.0.0.0:8000 &
script: python manage.py test functional_tests
before_install:
- openssl aes-256-cbc -K $encrypted_bc888766e2a8_key -iv $encrypted_bc888766e2a8_iv -in fixtures.tar.enc -out fixtures.tar -d
- tar xvf fixtures.tar
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
